#! package-manifest: deploy/olm-catalog/atlasmap-operator/0.0.1/atlasmap-operator.v0.0.1.clusterserviceversion.yaml
packageName: atlasmapapp-operator
channels:
  - name: beta
    currentCSV: atlasmap-operator.0.0.1
