apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"atlasmap.io/v1alpha1","kind":"AtlasMap","metadata":{"name":"example-atlasmap"},"spec":{"replicas":1}}]'
    capabilities: Basic Install
  name: atlasmap-operator.0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: AtlasMap
      name: atlasmaps.atlasmap.io
      version: v1alpha1
      description: An instance of AtlasMap
      displayName: AtlasMap
      specDescriptors:
      - description: Number of replicas
        displayName: Replicas
        path: replicas
  description: Placeholder description
  displayName: Atlasmap Operator
  install:
    spec:
      deployments:
      - name: atlasmap-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: atlasmap-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: atlasmap-operator
            spec:
              containers:
              - command:
                - atlasmap-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: atlasmap-operator
                image: docker.io/myeung18/atlasmap-operator
                imagePullPolicy: Always
                name: atlasmap-operator
                ports:
                - containerPort: 8383
                  name: metrics
                resources: {}
              serviceAccountName: atlasmap-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - atlasmap-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - atlasmap.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        - apiGroups:
          - extensions
          resources:
          - ingresses
          verbs:
          - '*'
        serviceAccountName: atlasmap-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.0.1
