apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: atlasmap-resources
      namespace: operator-lifecycle-manager
    data:
      clusterServiceVersions: |
        - apiVersion: operators.coreos.com/v1alpha1
          kind: ClusterServiceVersion
          metadata:
            annotations:
              alm-examples: '[{"apiVersion":"atlasmap.io/v1alpha1","kind":"AtlasMap","metadata":{"name":"example-atlasmap"},"spec":{"replicas":1}}]'
              capabilities: Basic Install
            name: atlasmap-operator.0.0.1
            namespace: placeholder
          spec:
            apiservicedefinitions: {}
            customresourcedefinitions:
              owned:
              - kind: AtlasMap
                name: atlasmaps.atlasmap.io
                version: v1alpha1
                description: An instance of AtlasMap
                displayName: AtlasMap
                specDescriptors:
                - description: Number of replicas
                  displayName: Replicas
                  path: replicas
            description: Placeholder description
            displayName: Atlasmap Operator
            install:
              spec:
                deployments:
                - name: atlasmap-operator
                  spec:
                    replicas: 1
                    selector:
                      matchLabels:
                        name: atlasmap-operator
                    strategy: {}
                    template:
                      metadata:
                        labels:
                          name: atlasmap-operator
                      spec:
                        containers:
                        - command:
                          - atlasmap-operator
                          env:
                          - name: WATCH_NAMESPACE
                            valueFrom:
                              fieldRef:
                                fieldPath: metadata.namespace
                          - name: POD_NAME
                            valueFrom:
                              fieldRef:
                                fieldPath: metadata.name
                          - name: OPERATOR_NAME
                            value: atlasmap-operator
                          image: docker.io/myeung18/atlasmap-operator
                          imagePullPolicy: Always
                          name: atlasmap-operator
                          ports:
                          - containerPort: 8383
                            name: metrics
                          resources: {}
                        serviceAccountName: atlasmap-operator
                permissions:
                - rules:
                  - apiGroups:
                    - ""
                    resources:
                    - pods
                    - services
                    - endpoints
                    - persistentvolumeclaims
                    - events
                    - configmaps
                    - secrets
                    verbs:
                    - '*'
                  - apiGroups:
                    - apps
                    resources:
                    - deployments
                    - daemonsets
                    - replicasets
                    - statefulsets
                    verbs:
                    - '*'
                  - apiGroups:
                    - monitoring.coreos.com
                    resources:
                    - servicemonitors
                    verbs:
                    - get
                    - create
                  - apiGroups:
                    - apps
                    resourceNames:
                    - atlasmap-operator
                    resources:
                    - deployments/finalizers
                    verbs:
                    - update
                  - apiGroups:
                    - atlasmap.io
                    resources:
                    - '*'
                    verbs:
                    - '*'
                  - apiGroups:
                    - route.openshift.io
                    resources:
                    - routes
                    verbs:
                    - '*'
                  - apiGroups:
                    - extensions
                    resources:
                    - ingresses
                    verbs:
                    - '*'
                  serviceAccountName: atlasmap-operator
              strategy: deployment
            installModes:
            - supported: true
              type: OwnNamespace
            - supported: true
              type: SingleNamespace
            - supported: false
              type: MultiNamespace
            - supported: true
              type: AllNamespaces
            maturity: alpha
            provider: {}
            version: 0.0.1
      customResourceDefinitions: |
        - apiVersion: apiextensions.k8s.io/v1beta1
          kind: CustomResourceDefinition
          metadata:
            name: atlasmaps.atlasmap.io
          spec:
            group: atlasmap.io
            names:
              kind: AtlasMap
              listKind: AtlasMapList
              plural: atlasmaps
              singular: atlasmap
            scope: Namespaced
            subresources:
              status: {}
              scale:
                specReplicasPath: .spec.replicas
                statusReplicasPath: .status.replicas
                labelSelectorPath: .status.labelSelector
            validation:
              openAPIV3Schema:
                properties:
                  apiVersion:
                    description: 'APIVersion defines the versioned schema of this representation
                      of an object. Servers should convert recognized schemas to the latest
                      internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
                    type: string
                  kind:
                    description: 'Kind is a string value representing the REST resource this
                      object represents. Servers may infer this from the endpoint the client
                      submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
                    type: string
                  metadata:
                    type: object
                  spec:
                    type: object
                  status:
                    type: object
            version: v1alpha1
            versions:
            - name: v1alpha1
              served: true
              storage: true
            additionalPrinterColumns:
              - name: URL
                description: AtlasMap URL
                type: string
                JSONPath: .status.URL
              - name: Image
                description: AtlasMap image
                type: string
                JSONPath: .status.image
      packages: >
        - #! package-manifest: deploy/olm-catalog/atlasmap-operator/0.0.1/atlasmap-operator.v0.0.1.clusterserviceversion.yaml
          packageName: atlasmapapp-operator
          channels:
            - name: beta
              currentCSV: atlasmap-operator.0.0.1

  - apiVersion: operators.coreos.com/v1alpha1
    kind: CatalogSource
    metadata:
      name: atlasmap-resources
      namespace: operator-lifecycle-manager
    spec:
      configMap: atlasmap-resources
      displayName: AtlasMap Operators
      publisher: Red Hat
      sourceType: internal
    status:
      configMapReference:
        name: atlasmap-resources
        namespace: operator-lifecycle-manager
